"""add contract_address to events

Revision ID: ac59f74875af
Revises: e12a0231a096
Create Date: 2026-06-16 11:18:02.019210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac59f74875af'
down_revision: Union[str, Sequence[str], None] = 'e12a0231a096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('contract_address', sa.String(length=42), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'contract_address')
    # ### end Alembic commands ###
